[api]
enabled = true
port = 54321
schemas = ["public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://web-alpha-three-24.vercel.app"
additional_redirect_urls = ["http://localhost:3000/**", "http://localhost:19876/callback", "https://web-alpha-three-24.vercel.app/**"]

[auth.external.google]
enabled = true
client_id = "68105588420-0lptan55qg7gt85u56qo2rtkv04rfd2m.apps.googleusercontent.com"
secret = "env(GOOGLE_CLIENT_SECRET)"
redirect_uri = "http://localhost:54321/auth/v1/callback"
